main_timer:
  rate: 20.0 # [Hz]

diagnostics_timer:
  rate: 10.0 # [Hz]

future_check_timer:
  rate: 10.0 # [Hz]

# the planner will integrate local maps into a global map
global_map:
  resolution: 0.05 # [m] voxel edge size
  fractor: 3 # [-]

euclidean_distance_cutoff: 1.0 # [m]
safe_obstacle_distance: 1.0 # [m]

distance_penalty: 1.0
greedy_penalty: 1.0

max_waypoint_distance: 0.0 # [m] // or set negative for no padding
min_altitude: -1000.0 # [m]
max_altitude: 1000.0 # [m]
unknown_is_occupied: false
replan_after: 1.0 # [s]

timeout_threshold: 1.5 # [s]
time_for_trajectory_generator: 0.3 # [s]

# visualization
points_scale: 0.22
lines_scale: 0.02
